"""initial

Revision ID: ac8db2ee5d14
Revises:
Create Date: 2026-05-11 19:13:01.465858

"""
from typing import Sequence, Union

from alembic import op, context
import sqlalchemy as sa

from dashboard_backend.src.util.passwords import hash_password


# revision identifiers, used by Alembic.
revision: str = 'ac8db2ee5d14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_settings_slug'), 'page_settings', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    # ### end Alembic commands ###

    # Seed default admin user
    app_config = context.get_context().config.attributes["app_config"]  # type: ignore
    default_username = app_config.backend_default_user_name
    default_password = app_config.backend_default_user_password
    op.execute(
        sa.text(
            "INSERT INTO users (username, password_hash, role) "
            "VALUES (:username, :password, 'admin')"
        ).bindparams(
            username=default_username,
            password=hash_password(default_password),
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_page_settings_slug'), table_name='page_settings')
    op.drop_table('page_settings')
    # ### end Alembic commands ###
