repos:
  - repo: local
    hooks:
      - id: ruff-fix-imports
        name: ruff fix imports
        entry: uv run ruff check --select I --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
