[project]
name = "data-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings==2.13.1",
    "pytest==9.0.3",
    "pytest-httpserver==1.1.5",
]

[dependency-groups]
dev = [
    "mypy==2.1.0",
    "pre-commit==4.6.0",
    "ruff==0.15.12",
]

[tool.uv.workspace]
members = [
    "data_loading",
    "python_common",
    "dashboard_backend",
]

[tool.ruff]
target-version = "py313"
line-length = 88
# fix = true    # enable autocorrections

include = [
    "data_loading/**/*.py",
    "dashboard_backend/**/*.py",
    "python_common/**/*.py",
]

[tool.ruff.lint]
select = [  # rules used
    "E",    # style errors
    "F",    # Pyflake errors
    "I",    # isort
    "UP"    # syntax upgrade
]
ignore = [
    "E402",     # Module level import not at top of file
    "F401"      # unused imports
]

[tool.mypy]
python_version = "3.13"
strict = true
# plugins = [
#     "pydantic.mypy",
#     "sqlalchemy.ext.mypy.plugin"
# ]
files = [
    "data_loading/",
    "dashboard_backend/",
    "python_common/"
]
