[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:airflow-api-server]
command=/app/.venv/bin/airflow api-server --host 0.0.0.0 --port %(ENV_AIRFLOW_PORT)s
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=AIRFLOW_HOME="/assets/airflow"

[program:airflow-scheduler]
command=/app/.venv/bin/airflow scheduler
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=AIRFLOW_HOME="/assets/airflow"

[program:airflow-dag-processor]
command=/app/.venv/bin/airflow dag-processor
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=AIRFLOW_HOME="/assets/airflow"
